MAX_AVAILABLE_AGENT_IN_CELL = 5

MIN_PROB_OF_TRANS_TO_BASE = 0.01
MIN_PROB_OF_TRANS_TO_RIOT = 0.01
MIN_PROB_OF_TRANS_TO_INJURED = 0.0

INITIAL_PROB_OF_RIOT = 0.1
INITIAL_PROB_OF_BASE = 1 - INITIAL_PROB_OF_RIOT
INITIAL_ROUND_OF_ENTRY_HOME = 1000
INITIAL_ROUND_OF_ENTRY_AWAY = 500

DOWNWARD_EXTRA_WEIGHT = 5
